### ISSUE TITLE
Add JitPack Instructions to Get Latest Commit

### ISSUE THREAD

**Issue by NoahBres** [NoahBres/MeepMeep#13]

**Comment by NoahBres** [comment]
for future reference, for jitpack projects you're able to pull dependencies with specific commits like so:
dependencies {
    // Specific tagged version
    implementation 'com.github.NoahBres:MeepMeep:2.0.1'

    // Pull from whatever the latest commit is
    implementation 'com.github.NoahBres:MeepMeep:-SNAPSHOT'

    // Pull from specific commit
    implementation 'com.github.NoahBres:MeepMeep:79d123f0c1'
}

**Comment by NoahBres** [comment]
![](https://cdn.discordapp.com/attachments/225451520911605765/1019359297769058335/CleanShot_2022-09-13_at_17.29.062x.jpg)

**Comment by olivia-banks** [comment]
Already implemented, orphaned issue; closing.
