### ISSUE TITLE
Robot Path Looping even Though Robot was Set to Not Loop

### ISSUE THREAD

**Issue by Dolphin2Point1** [NoahBres/MeepMeep#21]
Even though I ran `bot.setLooping(false)` the bot's still restarting the trajectory

**Comment by olivia-banks** [comment]
Hiya! [Rowland Hall Robotics](https://github.com/rh-robotics) has inherited ownership of MeepMeep, and we'll be doing maintenance from now on. That said, and given that this issue is over a year old, is this still a problem for anybody?
