### ISSUE TITLE
Using Variables from `DriveConstants` to Set Constraints

### ISSUE THREAD

**Issue by FormulaCarbon** [NoahBres/MeepMeep#26]
I was trying to use the DriveConstants file that is part of roadrunner to set up MeepMeep, in the `setConstraints()` function, but it gives me a "Cannot Resolve Symbol 'DriveConstants'" Error. I have checked the spelling and the location of the class is `org.firstinspires.ftc.teamcode.roadrunner_files.teamcode.drive.DriveConstants.MAX_ACCEL;`, which seems to be correct. I am wondering is there is a way to do this? If not, I would like it to be in the next update.

**Comment by olivia-banks** [comment]
Hiya! [Rowland Hall Robotics](https://github.com/rh-robotics) has inherited ownership of MeepMeep, and we'll be doing maintenance from now on. That said, and given that this issue is over a year old, is this still a problem for anybody?

**Comment by olivia-banks** [comment]
Closed due to inactivity.
