### ISSUE TITLE
Example is outdated

### ISSUE THREAD

**Issue by EddieDL** [NoahBres/MeepMeep#4]
It looks like your example documentation is outdated both on learnroadrunner.com and this repo. 

Based on my investigation it looks like you are now supposed to build a "Bot Entity", but it isn't 100% clear how to or what to do to get trajectories working.

Can you point me at a more current example?

**Comment by EddieDL** [comment]
Okay, I think I figured out my issue. The video says to take the latest version, which is 2.0.0. That version seems to be the issue. If I use 1.0.6, which is what is in the written examples things work.

Now my issue is that I really wanted to test out a trajectory that contains two splines. It doesn't look like the `DriveShim` class supports `.trajectoryBuilder`. Is there a way I can test out a single complex trajectory?

**Comment by NoahBres** [comment]
Very very sorry for neglecting this for so long. Been busy with life. Updated in the latest commit.

**Comment by EddieDL** [comment]
No problem @NoahBres thanks for the update.
