### ISSUE TITLE
Is It Possible To Change Coordinate System

### ISSUE THREAD

**Issue by Lexlogan312** [NoahBres/MeepMeep#42]
I am trying to use MeepMeep to run through my roadrunner paths, but our team's coordinates are rotated 90 degrees counterclockwise so the y-axis is side to side and the x-axis is up and down. Is there some way to change it to display in this orientation?

**Comment by teowelton** [comment]
Hi! This isn't a feature we intend to support. If you are still looking for a solution, you might want to create a simple method to convert between the two types of coordinates.
