### ISSUE TITLE
"Into the Deep" Version Bump

### ISSUE THREAD

**Issue by rowan-mcalpin** [NoahBres/MeepMeep#49]
Are we getting a version bump w/ Into the Deep field images? Or are you working on more changes before a version bump?

**Comment by NoahBres** [comment]
@DragonDev07

**Comment by teowelton** [comment]
Hey @rowan-mcalpin! I'm part of the [Rowland Hall Robotics](https://github.com/rh-robotics) teams (FTC Teams 19922, and 16748), and @IsaccBarker and I have recently taken over maintaining MeepMeep as Noah no longer has the time to manage this project. We're working on Into the Deep right now, and are trying to fix any remaining issues before hopefully moving the repository over to our organization and changing the package hosting. 

More info to come! :3

**Comment by rowan-mcalpin** [comment]
Interesting! Are you going to be making major changes to the system? My team doesn't use RR 1.0, and I'm hoping it'll still be usable with 0.5.x

**Comment by olivia-banks** [comment]
Yep! Our plan is to maintain the version being used with 0.5.x, and not really care too much about RoadRunner 1.0+, since A) not very many teams use it, and B) the documentation really isn't too good. We don't plan on making any major changes.

**Comment by rowan-mcalpin** [comment]
That's great! I'm an experienced Kotlin developer, so if you'd like any assistance, feel free to reach out!

**Comment by anpark1234** [comment]
I just ran into this same issue. It looks the into the deep images have been added to this project, but there hasn't been a version bump or release so you can't access the images directly from your MeepMeepTesting code using the enum yet (without downloading and compiling the project yourself). Thanks to team Juice 16236 for supplying the new field images.

I just worked around this using the following steps, and I'm posting them here in case it helps someone else:

1. Download the [image you want from the intothedeep folder](https://github.com/NoahBres/MeepMeep/tree/master/src/main/resources/background/season-2024-intothedeep).
2. Create a folder under MeepMeepTesting/src/main called resources (this is already configured as a resource folder for the gradle build).
3. Put the downloaded image in that folder.
4. Load the custom background in MeepMeepTesting.java as follows:

```
Image img = loadCustomBackgroundFromResource("/field-2024-juice-dark.png");
if (img != null) {
    meepMeep.setBackground(img);
}
else {
    meepMeep.setBackground(MeepMeep.Background.FIELD_CENTERSTAGE_JUICE_DARK);
}
meepMeep.setDarkMode(true).setBackgroundAlpha(0.95f).addEntity(myBot).start();
```

And add the following method to MeepMeepTesting.java (used in the code snippet above):

```
@SuppressWarnings("SameParameterValue")
private static Image loadCustomBackgroundFromResource(String name) {
    try {
        InputStream is = MeepMeepTesting.class.getResourceAsStream(name);
        assert is != null;
        return ImageIO.read(is);
    }
    catch (Exception e) {
        System.err.println("Unable to load custom background: " + e);
        return null;
    }
}
```

I prefer this resource approach to the approach mentioned in the README because you don't need to specify the full path to the image and it works cross-platform.

**Comment by teowelton** [comment]
Thanks for writing this out! Please read the comments above, a release will come, just fixing some issues first. I’d say by the end of the week ish :D

**Comment by anpark1234** [comment]
Ok, thanks. It's good to hear a new release is coming soon - I couldn't tell from the comments above how soon this would be.

FWIW, my vote would be to support RR 1.0 since 0.5 is deprecated. I suspect you'll find many teams are switching over to 1.0 now. Supporting both would probably be ideal if possible for now though.

**Comment by rowan-mcalpin** [comment]
> I just ran into this same issue. It looks the into the deep images have been added to this project, but there hasn't been a version bump or release so you can't access the images directly from your MeepMeepTesting code using the enum yet (without downloading and compiling the project yourself). Thanks to team Juice 16236 for supplying the new field images.
> 
> I just worked around this using the following steps, and I'm posting them here in case it helps someone else:
> 
> 1. Download the [image you want from the intothedeep folder](https://github.com/NoahBres/MeepMeep/tree/master/src/main/resources/background/season-2024-intothedeep).
> 2. Create a folder under MeepMeepTesting/src/main called resources (this is already configured as a resource folder for the gradle build).
> 3. Put the downloaded image in that folder.
> 4. Load the custom background in MeepMeepTesting.java as follows:
> 
> ```
> Image img = loadCustomBackgroundFromResource("/field-2024-juice-dark.png");
> if (img != null) {
>     meepMeep.setBackground(img);
> }
> else {
>     meepMeep.setBackground(MeepMeep.Background.FIELD_CENTERSTAGE_JUICE_DARK);
> }
> meepMeep.setDarkMode(true).setBackgroundAlpha(0.95f).addEntity(myBot).start();
> ```
> 
> And add the following method to MeepMeepTesting.java (used in the code snippet above):
> 
> ```
> @SuppressWarnings("SameParameterValue")
> private static Image loadCustomBackgroundFromResource(String name) {
>     try {
>         InputStream is = MeepMeepTesting.class.getResourceAsStream(name);
>         assert is != null;
>         return ImageIO.read(is);
>     }
>     catch (Exception e) {
>         System.err.println("Unable to load custom background: " + e);
>         return null;
>     }
> }
> ```
> 
> I prefer this resource approach to the approach mentioned in the README because you don't need to specify the full path to the image and it works cross-platform.

This would work but the easiest way to accomplish it is just using the `-SNAPSHOT` version that uses the latest commit, which has the image utilized. Google "JitPack snapshot" for details

**Comment by rowan-mcalpin** [comment]
Actually there's documentation in the readme about how to use the latest commit

**Comment by anpark1234** [comment]
> Actually there's documentation in the readme about how to use the latest commit

Oh! That is so much easier. Thanks for correcting me.

**Comment by rowan-mcalpin** [comment]
> Oh! That is so much easier. Thanks for correcting me.

Of course! Glad I could help!

**Comment by teowelton** [comment]
> > I just ran into this same issue. It looks the into the deep images have been added to this project, but there hasn't been a version bump or release so you can't access the images directly from your MeepMeepTesting code using the enum yet (without downloading and compiling the project yourself). Thanks to team Juice 16236 for supplying the new field images.
> > I just worked around this using the following steps, and I'm posting them here in case it helps someone else:
> > 
> > 1. Download the [image you want from the intothedeep folder](https://github.com/NoahBres/MeepMeep/tree/master/src/main/resources/background/season-2024-intothedeep).
> > 2. Create a folder under MeepMeepTesting/src/main called resources (this is already configured as a resource folder for the gradle build).
> > 3. Put the downloaded image in that folder.
> > 4. Load the custom background in MeepMeepTesting.java as follows:
> > 
> > ```
> > Image img = loadCustomBackgroundFromResource("/field-2024-juice-dark.png");
> > if (img != null) {
> >     meepMeep.setBackground(img);
> > }
> > else {
> >     meepMeep.setBackground(MeepMeep.Background.FIELD_CENTERSTAGE_JUICE_DARK);
> > }
> > meepMeep.setDarkMode(true).setBackgroundAlpha(0.95f).addEntity(myBot).start();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And add the following method to MeepMeepTesting.java (used in the code snippet above):
> > ```
> > @SuppressWarnings("SameParameterValue")
> > private static Image loadCustomBackgroundFromResource(String name) {
> >     try {
> >         InputStream is = MeepMeepTesting.class.getResourceAsStream(name);
> >         assert is != null;
> >         return ImageIO.read(is);
> >     }
> >     catch (Exception e) {
> >         System.err.println("Unable to load custom background: " + e);
> >         return null;
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I prefer this resource approach to the approach mentioned in the README because you don't need to specify the full path to the image and it works cross-platform.
> 
> This would work but the easiest way to accomplish it is just using the `-SNAPSHOT` version that uses the latest commit, which has the image utilized. Google "JitPack snapshot" for details

lol I can’t believe I forgot this even though I use it all the time, thanks!

**Comment by teowelton** [comment]
A version of MeepMeep supporting RoadRunner v0.5.6 has been released in the new repository:
https://github.com/rh-robotics/MeepMeep

Thanks everyone!
