### ISSUE TITLE
Jcenter had been shut down, so the whole repo doesn't work now

### ISSUE THREAD

**Issue by M0000se** [NoahBres/MeepMeep#6]
> Could not HEAD 'https://jcenter.bintray.com/com/github/NoahBres/MeepMeep/2.0.0/MeepMeep-2.0.0.pom'. Received status code 502 from server: Bad Gateway

**Comment by NoahBres** [comment]
MeepMeep is hosted on JitPack, not JCenter

The directions in the readme should work fine.
https://jitpack.io/#NoahBres/MeepMeep
