### ISSUE TITLE
`com.acmerobotics.roadrunner.geometry.Pose2d` Cannot be Accessed, Yet Gradle is Fine

### ISSUE THREAD

**Issue by timmyjr11** [NoahBres/MeepMeep#7]
So I tried to get MeepMeep on my own personal Android Studio code, so I followed the installation video and created the module, and used the Gradle snippet to quickly get the program up and running. To test to see if it worked, I used the sample code given to see it in action, problem is that 'Pose2d' could not be resolved, and could not access 'com.acmerobotics.roadrunner.geometry.Pose2d'

I have tried EVERYTHING, I've tried to Gradle sync, invalidate Cashes/Restart, Build > clean project, Build > Rebuild project, restarting the IDE

One of the solutions for the issue given from Android Studio is "Add library: 'Gradle: com.acmerobotics.roadrunner:core:0.5.4' to classpath" but when I press on the solution it does not do anything and I have no clue how to do this manually, how do I get this working?
![errorGang](https://user-images.githubusercontent.com/82425543/150625474-d249f2b1-744a-4000-ad30-435d8e09fef1.png)

**Comment by NoahBres** [comment]
I saw this mentioned in the Discord. Has this issue been resolved?

**Comment by timmyjr11** [comment]
> I saw this mentioned in the Discord. Has this issue been resolved?

Nope, not at all lol

**Comment by NoahBres** [comment]
Do you have `maven { url = 'https://maven.brott.dev/' }` somewhere in your gradle?

Does this help?
```
repositories {
  maven { url = 'https://maven.brott.dev/' }
  maven { url 'https://jitpack.io' }
}

dependencies {
  implementation 'com.github.NoahBres:MeepMeep:2.0.0'
}
```

**Comment by olivia-banks** [comment]
Hiya! [Rowland Hall Robotics](https://github.com/rh-robotics) has inherited ownership of MeepMeep, and we'll be doing maintenance from now on. That said, and given that this issue is over a year old, is this still a problem for anybody?

**Comment by olivia-banks** [comment]
Closing, due to the fact that the suggested solution is already present in the documentation.
