### ISSUE TITLE
Custom Field Dimensions Interface

### ISSUE THREAD

**Issue by EddieDL** [NoahBres/MeepMeep#8]
I would like to use Meep Meep for a different game. The field size, shape and background are completely different. Is there a way to make this happen without forking Meep Meep?

**Comment by NoahBres** [comment]
There is an interface for changing the background but not the field dimensions

**Comment by EddieDL** [comment]
Thanks for the info. I am going to work with scaling between the two fields for the moment, but might try to implement something else in the future.

**Comment by NoahBres** [comment]
Changed this from a question to issue so hopefully I can get around to this!

**Comment by olivia-banks** [comment]
This is outside the scope of the project, and implementation would complicate the codebase more than we're willing to deal with in the short term.
