### ISSUE TITLE
"class file for java.awt.Image not found"

### ISSUE THREAD

**Issue by TWinston-66** [NoahBres/MeepMeep#9]
When running the sample code, on the line below, I get the error "class file for java.awt.Image not found"

meepMeep.setBackground(MeepMeep.Background.FIELD_FREIGHTFRENZY_ADI_DARK);

**Comment by NoahBres** [comment]
You've most likely set your run configuration to an Android app. 
https://youtu.be/vdn1v404go8 (see around 7 minutes). The run target should be an "Application"

**Comment by TWinston-66** [comment]
Is this the correct config? 
![Screenshot from 2022-03-08 12-18-32](https://user-images.githubusercontent.com/65579453/157309588-322047f1-484b-42e6-9dea-2ccd16c0ac1a.png)

**Comment by NoahBres** [comment]
Looks to be correct. Are you still encountering that error with the given config?

**Comment by TWinston-66** [comment]
Yeah I am... 
![Screenshot from 2022-03-08 14-47-49](https://user-images.githubusercontent.com/65579453/157331035-6a172816-fcf8-42c0-8e9e-cdef09484b3e.png)

**Comment by TWinston-66** [comment]
I've tested it on both Windows and Linux machines and it's broken in both. Is there a version of the JDK or something I need that I am missing?

**Comment by TWinston-66** [comment]
I got it to work by installing it into an Intelli J project using JDK 16 SE. 
![Uploading Screenshot from 2022-03-10 11-31-23.png…]()

**Comment by NoahBres** [comment]
Hm. That's very interesting. I'm not sure why your own JDK/JRE versions don't include the awt packages. I use JDK 11 in my testing so its not a version issue. 

I don't really have any insight I can provide regarding this. Apologies. I am glad it is working now!
